// import { Injectable } from '@angular/core';
// import jsPDF from 'jspdf';

// @Injectable({
//   providedIn: 'root',
// })
// export class PdfPayrollService {
//   generatePayrollPDF(payroll: any, employee: any) {
//     const doc = new jsPDF('p', 'mm', 'a4');

//     // ---------- HEADER ----------
//     doc.setFont('Helvetica', 'bold');
//     doc.setFontSize(20);
//     doc.text('COMPANY PAYROLL STATEMENT', 105, 15, { align: 'center' });

//     doc.setFontSize(11);
//     doc.setFont('Helvetica', 'normal');
//     doc.text('Generated by EMS Payroll System', 105, 22, { align: 'center' });

//     doc.line(10, 25, 200, 25); // line under header

//     // ---------- EMPLOYEE INFORMATION ----------
//     doc.setFontSize(13);
//     doc.setFont('Helvetica', 'bold');
//     doc.text('EMPLOYEE INFORMATION', 10, 35);
//     doc.setFont('Helvetica', 'normal');

//     doc.setFontSize(11);
//     doc.text(`Employee Name:  ${employee.name}`, 10, 45);
//     doc.text(`Employee ID:     ${employee.employee_id}`, 10, 52);
//     doc.text(`Department:       ${employee.department_name}`, 10, 59);
//     doc.text(`Month:              ${payroll.month}`, 10, 66);

//     // ---------- ATTENDANCE SUMMARY BOX ----------
//     doc.setFillColor(240, 240, 240);
//     doc.roundedRect(10, 75, 190, 40, 3, 3, 'F');

//     doc.setFontSize(13);
//     doc.setFont('Helvetica', 'bold');
//     doc.text('Attendance Summary', 15, 85);

//     doc.setFontSize(11);
//     doc.setFont('Helvetica', 'normal');

//     doc.text(`Total Working Days :  ${payroll.total_working_days}`, 15, 95);
//     doc.text(`Present :                  ${payroll.total_present}`, 105, 95);

//     doc.text(`Absent :                  ${payroll.total_absent}`, 15, 102);
//     doc.text(`Worked Hours :         ${payroll.total_hours} hrs`, 105, 102);

//     doc.text(`Overtime Hours :      ${payroll.overtime_hours} hrs`, 15, 109);

//     // ---------- SALARY BREAKDOWN ----------
//     doc.setFontSize(13);
//     doc.setFont('Helvetica', 'bold');
//     doc.text('Salary Breakdown', 10, 135);

//     doc.line(10, 137, 70, 137);

//     const startY = 145;

//     this.drawSalaryRow(doc, 'Basic Salary', payroll.basic_salary, startY);
//     this.drawSalaryRow(doc, 'Overtime Pay', payroll.overtime_pay, startY + 8);
//     this.drawSalaryRow(doc, 'Deductions', payroll.deductions, startY + 16);

//     // NET SALARY BOX
//     doc.setFillColor(220, 245, 220);
//     doc.roundedRect(10, startY + 28, 190, 15, 3, 3, 'F');

//     doc.setFontSize(14);
//     doc.setFont('Helvetica', 'bold');
//     doc.text(`NET SALARY:  Rs ${payroll.net_salary}`, 15, startY + 38);

//     // ---------- FOOTER ----------
//     doc.setFontSize(11);
//     doc.setFont('Helvetica', 'normal');
//     doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 10, 270);
//     doc.text('HR Signature: ___________________________', 10, 280);

//     // ---------- SAVE ----------
//     doc.save(`payroll_${employee.employee_id}_${payroll.month}.pdf`);
//   }

//   private drawSalaryRow(doc: any, label: string, amount: string, y: number) {
//     doc.setFontSize(11);
//     doc.setFont('Helvetica', 'normal');
//     doc.text(label, 15, y);
//     doc.text(`Rs ${amount}`, 180, y, { align: 'right' });
//   }
// }


import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';

@Injectable({
  providedIn: 'root',
})
export class PdfPayrollService {
  generatePayrollPDF(payroll: any, employee: any) {
    const doc = new jsPDF('p', 'mm', 'a4');

    // ============================
    // HEADER
    // ============================
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('STAFFX PAYROLL STATEMENT', 105, 20, { align: 'center' });

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by StaffX HR & Payroll System', 105, 27, { align: 'center' });

    doc.setDrawColor(50, 50, 50);
    doc.line(15, 32, 195, 32);

    // ============================
    // EMPLOYEE INFO SECTION
    // ============================
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('EMPLOYEE INFORMATION', 15, 42);

    const infoY = 50;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    doc.text(`Employee Name :  ${employee.name}`, 15, infoY);
    doc.text(`Employee ID   :  ${employee.employee_id}`, 15, infoY + 7);
    doc.text(`Department    :  ${employee.department_name}`, 15, infoY + 14);
    doc.text(`Month         :  ${payroll.month}`, 15, infoY + 21);

    // ============================
    // ATTENDANCE SUMMARY BOX
    // ============================
    const boxY = infoY + 30;

    doc.setFillColor(245, 245, 245);
    doc.roundedRect(15, boxY, 180, 40, 3, 3, 'F');

    doc.setFont('helvetica', 'bold');
    doc.text('Attendance Summary', 20, boxY + 8);

    doc.setFont('helvetica', 'normal');

    doc.text(`Total Working Days : ${payroll.total_working_days}`, 20, boxY + 18);
    doc.text(`Absent : ${payroll.total_absent}`, 20, boxY + 26);
    doc.text(`Overtime Hours : ${payroll.overtime_hours} hrs`, 20, boxY + 34);

    doc.text(`Present : ${payroll.total_present}`, 120, boxY + 18);
    doc.text(`Worked Hours : ${payroll.total_hours} hrs`, 120, boxY + 26);

    // ============================
    // SALARY BREAKDOWN
    // ============================
    const salaryY = boxY + 55;

    doc.setFont('helvetica', 'bold');
    doc.text('Salary Breakdown', 15, salaryY);

    doc.line(15, salaryY + 2, 195, salaryY + 2);

    doc.setFont('helvetica', 'normal');
    doc.text('Basic Salary', 20, salaryY + 12);
    doc.text(`Rs ${payroll.basic_salary}`, 170, salaryY + 12, { align: 'right' });

    doc.text('Overtime Pay', 20, salaryY + 20);
    doc.text(`Rs ${payroll.overtime_pay}`, 170, salaryY + 20, { align: 'right' });

    doc.text('Deductions', 20, salaryY + 28);
    doc.text(`Rs ${payroll.deductions}`, 170, salaryY + 28, { align: 'right' });

    // ============================
    // NET SALARY BOX
    // ============================
    const netY = salaryY + 40;

    doc.setFillColor(214, 255, 214);
    doc.roundedRect(15, netY, 180, 18, 3, 3, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(0, 80, 0);
    doc.text(`NET SALARY:  Rs ${payroll.net_salary}`, 25, netY + 12);

    doc.setTextColor(0, 0, 0);

    // ============================
    // FOOTER
    // ============================
    const footerY = netY + 35;
    doc.setFontSize(10);

    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 15, footerY);

    doc.text('HR Signature: ____________________________', 15, footerY + 10);

    // Save PDF
    doc.save(`payroll_${employee.employee_id}_${payroll.month}.pdf`);
  }
}
